-- ============================================
-- PowerOps 数据库初始化脚本 (Oracle 19c)
-- 简化版：6 表，无 BILL/INSPECTION_PLAN
-- ============================================

-- ============================================
-- 1. 系统用户表
-- ============================================
CREATE TABLE SYS_USER (
    USER_ID     NUMBER PRIMARY KEY,
    USERNAME    VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(100) NOT NULL,
    REAL_NAME   VARCHAR2(50),
    PHONE       VARCHAR2(20),
    ROLE_CODE   VARCHAR2(20) NOT NULL CHECK (ROLE_CODE IN ('ADMIN', 'OPERATOR', 'MERCHANT')),
    STATUS      NUMBER DEFAULT 1 CHECK (STATUS IN (0, 1)),
    CREATE_TIME DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SYS_USER IS '系统用户表';
COMMENT ON COLUMN SYS_USER.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER.USERNAME IS '用户名';
COMMENT ON COLUMN SYS_USER.PASSWORD IS '密码';
COMMENT ON COLUMN SYS_USER.REAL_NAME IS '真实姓名';
COMMENT ON COLUMN SYS_USER.PHONE IS '手机号';
COMMENT ON COLUMN SYS_USER.ROLE_CODE IS '角色: ADMIN-管理员, OPERATOR-运维人员, MERCHANT-商户';
COMMENT ON COLUMN SYS_USER.STATUS IS '状态: 0-禁用, 1-启用';

-- ============================================
-- 2. 商铺表
-- ============================================
CREATE TABLE SHOP (
    SHOP_ID        NUMBER PRIMARY KEY,
    SHOP_NO        VARCHAR2(50),
    SHOP_NAME      VARCHAR2(100) NOT NULL,
    BUILDING       VARCHAR2(50),
    FLOOR_NO       VARCHAR2(20),
    BUSINESS_TYPE  VARCHAR2(50),
    CONTACT_PERSON VARCHAR2(50),
    CONTACT_PHONE  VARCHAR2(20),
    STATUS         NUMBER DEFAULT 1 CHECK (STATUS IN (0, 1, 2)),
    CREATE_TIME    DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SHOP IS '商铺表';
COMMENT ON COLUMN SHOP.SHOP_ID IS '商铺ID';
COMMENT ON COLUMN SHOP.SHOP_NO IS '商铺编号';
COMMENT ON COLUMN SHOP.SHOP_NAME IS '商铺名称';
COMMENT ON COLUMN SHOP.BUILDING IS '楼栋';
COMMENT ON COLUMN SHOP.FLOOR_NO IS '楼层';
COMMENT ON COLUMN SHOP.BUSINESS_TYPE IS '业态类型: 餐饮/零售/服务';
COMMENT ON COLUMN SHOP.CONTACT_PERSON IS '联系人';
COMMENT ON COLUMN SHOP.CONTACT_PHONE IS '联系电话';
COMMENT ON COLUMN SHOP.STATUS IS '状态: 0-停用, 1-营业中, 2-装修中';

-- ============================================
-- 3. 设备表
-- ============================================
CREATE TABLE DEVICE (
    DEVICE_ID   NUMBER PRIMARY KEY,
    DEVICE_NO   VARCHAR2(50),
    DEVICE_NAME VARCHAR2(100) NOT NULL,
    DEVICE_TYPE VARCHAR2(50) NOT NULL,
    SHOP_ID     NUMBER,
    STATUS      VARCHAR2(20) DEFAULT '运行',
    CONSTRAINT FK_DEVICE_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID)
);

COMMENT ON TABLE DEVICE IS '设备表';
COMMENT ON COLUMN DEVICE.DEVICE_ID IS '设备ID';
COMMENT ON COLUMN DEVICE.DEVICE_NO IS '设备编号';
COMMENT ON COLUMN DEVICE.DEVICE_NAME IS '设备名称';
COMMENT ON COLUMN DEVICE.DEVICE_TYPE IS '设备类型: 变压器/配电柜/断路器/智能电表/漏电保护器';
COMMENT ON COLUMN DEVICE.SHOP_ID IS '所属商铺ID';
COMMENT ON COLUMN DEVICE.STATUS IS '状态: 运行/故障/检修';

-- ============================================
-- 4. 用电记录表
-- ============================================
CREATE TABLE POWER_RECORD (
    RECORD_ID   NUMBER PRIMARY KEY,
    SHOP_ID     NUMBER NOT NULL,
    RECORD_DATE DATE NOT NULL,
    CONSUMPTION NUMBER(10,2),
    CONSTRAINT FK_POWER_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID)
);

COMMENT ON TABLE POWER_RECORD IS '用电记录表';
COMMENT ON COLUMN POWER_RECORD.RECORD_ID IS '记录ID';
COMMENT ON COLUMN POWER_RECORD.SHOP_ID IS '商铺ID';
COMMENT ON COLUMN POWER_RECORD.RECORD_DATE IS '记录日期';
COMMENT ON COLUMN POWER_RECORD.CONSUMPTION IS '用电量(kWh)';

-- ============================================
-- 5. 报警表
-- ============================================
CREATE TABLE ALARM (
    ALARM_ID    NUMBER PRIMARY KEY,
    DEVICE_ID   NUMBER NOT NULL,
    ALARM_TYPE  VARCHAR2(50) NOT NULL,
    ALARM_LEVEL VARCHAR2(20) NOT NULL CHECK (ALARM_LEVEL IN ('一般', '严重', '紧急')),
    ALARM_TIME  DATE DEFAULT SYSDATE,
    STATUS      VARCHAR2(20) DEFAULT '未处理',
    HANDLER_ID  NUMBER,
    HANDLE_TIME DATE,
    CONSTRAINT FK_ALARM_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(DEVICE_ID)
);

COMMENT ON TABLE ALARM IS '报警表';
COMMENT ON COLUMN ALARM.ALARM_ID IS '报警ID';
COMMENT ON COLUMN ALARM.DEVICE_ID IS '设备ID';
COMMENT ON COLUMN ALARM.ALARM_TYPE IS '报警类型: 过压/欠压/过流/过载/漏电/温度过高';
COMMENT ON COLUMN ALARM.ALARM_LEVEL IS '报警等级: 一般/严重/紧急';
COMMENT ON COLUMN ALARM.STATUS IS '状态: 未处理/已确认/已解决';

-- ============================================
-- 6. 工单表
-- ============================================
CREATE TABLE WORK_ORDER (
    ORDER_ID     NUMBER PRIMARY KEY,
    ORDER_NO     VARCHAR2(50) NOT NULL UNIQUE,
    ORDER_TYPE   VARCHAR2(20) NOT NULL,
    DEVICE_ID    NUMBER,
    APPLICANT_ID NUMBER,
    HANDLER_ID   NUMBER,
    PRIORITY     VARCHAR2(20) DEFAULT '普通',
    DESCRIPTION  VARCHAR2(1000),
    STATUS       VARCHAR2(20) DEFAULT '待处理',
    CREATE_TIME  DATE DEFAULT SYSDATE,
    FINISH_TIME  DATE,
    CONSTRAINT FK_WO_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(DEVICE_ID)
);

COMMENT ON TABLE WORK_ORDER IS '工单表';
COMMENT ON COLUMN WORK_ORDER.ORDER_ID IS '工单ID';
COMMENT ON COLUMN WORK_ORDER.ORDER_NO IS '工单编号(自动生成)';
COMMENT ON COLUMN WORK_ORDER.ORDER_TYPE IS '工单类型: 维修/抢修';
COMMENT ON COLUMN WORK_ORDER.PRIORITY IS '优先级: 普通/高/紧急';
COMMENT ON COLUMN WORK_ORDER.STATUS IS '状态: 待处理/处理中/已完成';

-- ============================================
-- 创建序列
-- ============================================
CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHOP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEVICE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POWER_RECORD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALARM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WORK_ORDER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================
-- 插入测试数据
-- ============================================

-- 用户数据 (密码: admin123 / operator123 / merchant123)
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'admin', 'admin123', '系统管理员', '13800138000', 'ADMIN', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'operator1', 'operator123', '运维人员1', '13800138001', 'OPERATOR', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'merchant1', 'merchant123', '商户用户1', '13800138002', 'MERCHANT', 1);

-- 商铺数据
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S001', '星巴克咖啡', 'A栋', '1层', '餐饮', '张三', '13900139001', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S002', '优衣库', 'A栋', '2层', '零售', '李四', '13900139002', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S003', '万达影城', 'B栋', '3层', '娱乐', '王五', '13900139003', 1);

-- 设备数据
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D001', '星巴克配电柜', '配电柜', 1, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D002', '星巴克电表', '智能电表', 1, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D003', '优衣库电表', '智能电表', 2, '运行');

-- 用电记录数据
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 1, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 120.5);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 2, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 250.8);

-- 报警数据
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 2, '过压', '严重', '未处理');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 3, '过流', '一般', '未处理');

-- ============================================
-- 60条补充测试数据
-- ============================================

-- 用户数据 (再接7条，共10用户)
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'operator2', 'operator123', '李工', '13800138003', 'OPERATOR', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'operator3', 'operator123', '王工', '13800138004', 'OPERATOR', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'merchant2', 'merchant123', '星巴克负责人', '13800138005', 'MERCHANT', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'merchant3', 'merchant123', '优衣库负责人', '13800138006', 'MERCHANT', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'merchant4', 'merchant123', '万达影城负责人', '13800138007', 'MERCHANT', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'merchant5', 'merchant123', '麦当劳负责人', '13800138008', 'MERCHANT', 1);
INSERT INTO SYS_USER (USER_ID, USERNAME, PASSWORD, REAL_NAME, PHONE, ROLE_CODE, STATUS)
VALUES (SEQ_SYS_USER.NEXTVAL, 'merchant6', 'merchant123', '海底捞负责人', '13800138009', 'MERCHANT', 1);

-- 商铺数据 (再接7条，共10商铺)
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S004', '麦当劳', 'B栋', '1层', '餐饮', '赵六', '13900139004', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S005', '名创优品', 'B栋', '2层', '零售', '钱七', '13900139005', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S006', '海底捞', 'C栋', '1层', '餐饮', '孙八', '13900139006', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S007', '周大福', 'C栋', '2层', '零售', '周九', '13900139007', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S008', '小米之家', 'A栋', '3层', '零售', '吴十', '13900139008', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S009', '奈雪的茶', 'B栋', '1层', '餐饮', '郑一', '13900139009', 1);
INSERT INTO SHOP (SHOP_ID, SHOP_NO, SHOP_NAME, BUILDING, FLOOR_NO, BUSINESS_TYPE, CONTACT_PERSON, CONTACT_PHONE, STATUS)
VALUES (SEQ_SHOP.NEXTVAL, 'S010', '屈臣氏', 'C栋', '3层', '零售', '陈二', '13900139010', 1);

-- 设备数据 (再接13条，共16设备)
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D004', '优衣库配电柜', '配电柜', 2, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D005', '万达影城配电柜', '配电柜', 3, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D006', '麦当劳配电柜', '配电柜', 4, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D007', '海底捞配电柜', '配电柜', 6, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D008', '万达影城电表', '智能电表', 3, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D009', '麦当劳电表', '智能电表', 4, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D010', '名创优品电表', '智能电表', 5, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D011', '海底捞电表', '智能电表', 6, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D012', '小米之家电表', '智能电表', 8, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D013', '奈雪电表', '智能电表', 9, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D014', '屈臣氏电表', '智能电表', 10, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D015', '周大福电表', '智能电表', 7, '运行');
INSERT INTO DEVICE (DEVICE_ID, DEVICE_NO, DEVICE_NAME, DEVICE_TYPE, SHOP_ID, STATUS)
VALUES (SEQ_DEVICE.NEXTVAL, 'D016', '星巴克断路器', '断路器', 1, '运行');

-- 用电记录 (再接13条，共15记录)
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 1, TO_DATE('2026-06-02', 'YYYY-MM-DD'), 118.3);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 2, TO_DATE('2026-06-02', 'YYYY-MM-DD'), 245.6);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 3, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 890.2);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 4, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 560.1);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 5, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 320.4);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 6, TO_DATE('2026-06-01', 'YYYY-MM-DD'), 780.5);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 1, TO_DATE('2026-06-03', 'YYYY-MM-DD'), 125.7);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 2, TO_DATE('2026-06-03', 'YYYY-MM-DD'), 238.9);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 3, TO_DATE('2026-06-02', 'YYYY-MM-DD'), 875.3);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 4, TO_DATE('2026-06-02', 'YYYY-MM-DD'), 555.6);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 1, TO_DATE('2026-06-04', 'YYYY-MM-DD'), 130.1);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 2, TO_DATE('2026-06-04', 'YYYY-MM-DD'), 242.3);
INSERT INTO POWER_RECORD (RECORD_ID, SHOP_ID, RECORD_DATE, CONSUMPTION)
VALUES (SEQ_POWER_RECORD.NEXTVAL, 5, TO_DATE('2026-06-02', 'YYYY-MM-DD'), 315.8);

-- 报警数据 (再接8条，共10报警)
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 4, '过压', '紧急', '已确认');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 4, '过流', '一般', '未处理');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 5, '漏电', '严重', '已解决');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 6, '温度过高', '紧急', '未处理');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 8, '欠压', '一般', '已确认');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 9, '过载', '严重', '未处理');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 10, '过流', '一般', '已解决');
INSERT INTO ALARM (ALARM_ID, DEVICE_ID, ALARM_TYPE, ALARM_LEVEL, STATUS)
VALUES (SEQ_ALARM.NEXTVAL, 11, '过压', '紧急', '未处理');

-- 工单数据 (再接12条，共12工单)
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618002', '维修', 4, 4, 2, '高', '优衣库配电柜过压报警', '处理中', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618003', '抢修', 5, 4, 2, '紧急', '万达影城配电柜温度过高', '待处理', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618004', '维修', 8, 5, 1, '普通', '星巴克断路器定期检修', '处理中', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618005', '抢修', 6, 4, 2, '紧急', '麦当劳配电柜漏电', '待处理', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618006', '维修', 9, 5, 2, '普通', '麦当劳电表校准', '已完成', SYSDATE);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618007', '维修', 10, 7, 1, '高', '名创优品电表过载处理', '处理中', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618008', '抢修', 11, 8, 2, '紧急', '海底捞电表过压报警', '待处理', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618009', '维修', 12, 9, 2, '普通', '小米之家电表定期巡检', '已完成', SYSDATE);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618010', '维修', 13, 10, 1, '高', '奈雪电表维护', '处理中', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618011', '抢修', 14, 4, 2, '紧急', '屈臣氏电表过流', '待处理', NULL);
INSERT INTO WORK_ORDER (ORDER_ID, ORDER_NO, ORDER_TYPE, DEVICE_ID, APPLICANT_ID, HANDLER_ID, PRIORITY, DESCRIPTION, STATUS, FINISH_TIME)
VALUES (SEQ_WORK_ORDER.NEXTVAL, 'WO20260618012', '维修', 15, 7, 1, '普通', '周大福电表线路检查', '已完成', SYSDATE);

COMMIT;

-- ============================================
-- 创建索引
-- ============================================
CREATE INDEX IDX_SYS_USER_USERNAME ON SYS_USER(USERNAME);
CREATE INDEX IDX_SYS_USER_ROLE_CODE ON SYS_USER(ROLE_CODE);
CREATE INDEX IDX_SYS_USER_STATUS ON SYS_USER(STATUS);
CREATE INDEX IDX_SHOP_BUILDING ON SHOP(BUILDING);
CREATE INDEX IDX_SHOP_TYPE ON SHOP(BUSINESS_TYPE);
CREATE INDEX IDX_DEVICE_SHOP ON DEVICE(SHOP_ID);
CREATE INDEX IDX_DEVICE_TYPE ON DEVICE(DEVICE_TYPE);
CREATE INDEX IDX_DEVICE_STATUS ON DEVICE(STATUS);
CREATE INDEX IDX_POWER_SHOP ON POWER_RECORD(SHOP_ID);
CREATE INDEX IDX_POWER_DATE ON POWER_RECORD(RECORD_DATE);
CREATE INDEX IDX_ALARM_DEVICE ON ALARM(DEVICE_ID);
CREATE INDEX IDX_ALARM_STATUS ON ALARM(STATUS);
CREATE INDEX IDX_WO_STATUS ON WORK_ORDER(STATUS);
CREATE INDEX IDX_WO_HANDLER ON WORK_ORDER(HANDLER_ID);


